### ISSUE TITLE
Error while comiling

### ISSUE THREAD

**Issue by rmrbytes** [difhel/cython-fastapi-example#1]
Hello @difhel

This is what I was looking for. However, when I ran your code as-is (with no changes) I get the following error.

```
cython main.pyx
/home/rmr/.local/lib/python3.9/site-packages/Cython/Compiler/Main.py:381: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: /home/rmr/Projects/cython-fastapi-example/main.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)
python3.10 setup.py build_ext --build-lib=.
make: python3.10: No such file or directory
make: *** [Makefile:24: build] Error 127
```

I am using Linux.

Thanks.

**Comment by difhel** [comment]
Hello!
You should specify your Python version [here](https://github.com/difhel/cython-fastapi-example/blob/master/Makefile#L10). As I see from your log, your Python version is 3.9.
Let me know if you still encourage this issue.

**Comment by rmrbytes** [comment]
Yup. That worked. Thanks. Now, I will replace it with my own code.

**Comment by rmrbytes** [comment]
In case I require a single executable is there a way to use the `.so` with a utility like PyInstaller? Thanks
